---
- name: piholeupdate
  hosts: 192.168.0.110
  become: yes
  become_method: sudo
  
  tasks:
  
  - name: update gravity
     ansible.builtin.shell:
      cmd: pihole updateGravity

  - name: update pihole
    ansible.builtin.shell:
      cmd: pihole -up
