---
- name: Send Text Message
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send SMS
      uri:
        url: "https://api.twilio.com/2010-04-01/Accounts/ACd6504b9eeecfc449b2a4f36422bc2024/Messages.json"
        method: POST
        headers:
          Authorization: "Basic a5464917002ce6025051ade7f3aef309"
        body_format: form-urlencoded
        body:
          From: "14124197529"  # Replace with your Twilio phone number
          To: "17039730954"  # Replace with the target phone number
          Body: "This is a test message for my automated bot."  # Replace with your desired message
      register: response

    - name: Check Response
      debug:
        var: response
