---
- name: Download latest wikipedia archive
  hosts: 192.168.0.162
  gather_facts: false
  tasks:
  - name: Retrieve wikipedia archive page
    uri:
      url: "https://dumps.wikimedia.org/backup-index.html"
      return_content: yes
    register: archive_page

  - name: Set archive URL
    set_fact:
      archive_url: "{{ archive_page.content | regex_findall('href=\"(enwiki-.*?.bz2)\"') | first }}"

  - name: Download wikipedia archive
    get_url:
      url: "https://dumps.wikimedia.org/{{ archive_url }}"
      dest: "/home/kurt/Downloads/wiki/enwiki-latest.bz2"

  - name: Delete old wikipedia archives
    file:
      path: "/home/kurt/Downloads/wiki/{{ item }}"
      state: absent
    with_fileglob:
      - "/home/kurt/Downloads/wiki/enwiki-*"
      exclude:
        - "/home/kurt/Downloads/wiki/enwiki-latest.bz2"
