---
- name: Update Wiki Archive
  hosts: 192.168.0.162
  become: yes
  gather_facts: no

  tasks:
    - name: Check if wiki archive exists
      stat:
        path: /home/kurt/wiki/enwiki-latest-pages-articles.xml.bz2
      register: wiki_archive

    - name: Download wiki archive
      when: wiki_archive.stat.exists == false
      get_url:
        url: https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2
        dest: /home/kurt/wiki/enwiki-latest-pages-articles.xml.bz2
        mode: 0644

    - name: Create wiki archive directory
      file:
        path: /home/kurt/wiki/
        state: directory
        mode: 0755

    - name: Extract wiki archive
      command: bunzip2 -k /home/kurt/wiki/enwiki-latest-pages-articles.xml.bz2
      args:
        creates: /home/kurt/wiki/enwiki-latest-pages-articles.xml

    - name: Generate wiki HTML
      command: wikixml2html /home/kurt/wiki/enwiki-latest-pages-articles.xml /home/kurt/wiki/index.html
      args:
        creates: /home/kurt/wiki/index.html

    - name: Set archive URL
      set_fact:
        archive_url: "https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2"

    - name: Delete old wiki archives
      become: yes
      shell: "rm -f /home/kurt/wiki/enwiki-*.bz2"
      args:
        warn: false

    - name: Keep only latest wiki archive
      become: yes
      shell: "ls -t /home/kurt/wiki/enwiki-*.xml | tail -n +2 | xargs rm -f"
      args:
        warn: false
